/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package annotations;

import org.junit.jupiter.api.Test;

class MyCustomAnnotationTest {
    @Test
    void testMyCustomAnnotation() {
        Example example = new Example();

        MyCustomAnnotation annotation = example.getClass().getAnnotation(MyCustomAnnotation.class);
        System.out.println(annotation);
        System.out.println("someBooleanValueWithDefault: " + annotation.someBooleanValueWithDefault());
        System.out.println("someBooleanValueWithNoDefault: " + annotation.someBooleanValueWithNoDefault());
    }
}
