/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
@interface MyCustomAnnotation {
    boolean someBooleanValueWithDefault() default true;

    boolean someBooleanValueWithNoDefault();
}
