/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package immutability;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertThrows;

class AppTest {
    static ArrayList<String> list = new ArrayList<>();

    @BeforeAll
    static void setup() {
        list.add("something");
        list.add("another thing");
    }

    @Nested
    class ImmutableList {
        @Test()
        void setOperation() {
            List<String> immutableList = Collections.unmodifiableList(list);
            assertThrows(UnsupportedOperationException.class, () -> immutableList.set(0, "ok"));
        }

        @Test()
        void addOperation() {
            List<String> immutableList = Collections.unmodifiableList(list);
            assertThrows(UnsupportedOperationException.class, () -> immutableList.add("ok"));
        }
    }
}
